fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! init

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,7 +30,7 @@ jobs:
       - run: echo "Buld stuff ${{ matrix.target }}"
       - run: sleep 5
       - run: |
-          if [ "${{ matrix.target }}" == "a" ] ; then exit 1; fi;
+          if [ "${{ matrix.target }}" == "0" ] ; then exit 1; fi;
       - run: echo "Buld done!"
 
   # Workarround so that there is a single job for the status check
@@ -42,6 +42,11 @@ jobs:
     steps:
       - run: |
           echo "Needs context: ${{ toJson(needs) }}"
+#      - name: Error out because there is a failure
+#        if: ${{ needs.build.result !=  }}
+#        run: |
+#          echo "One or more builds failed."
+#          exit 1
       - name: Error out because there is a failure
         if: ${{ failure() }}
         run: |
